name: CI & Release

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build:
        name: Build multi plataforma
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux, windows, darwin] # Linux, Windows e macOS
                goarch: [amd64]

        defaults:
            run:
                working-directory: projects/cmd

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Configurar Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.26.x'

            - name: Download dependências
              run: go mod download

            - name: Extract Version
              id: version
              shell: bash
              run: |
                  # Extrai a versão a partir do código Go
                  RAW_VERSION=$(grep -oP 'var version = "\K[^"]+' cmd/assinatura.go)
                  VERSION="v$RAW_VERSION"
                  echo "VERSION=$VERSION" >> $GITHUB_ENV

                  # Verifica se a tag já existe no repositório
                  if git ls-remote --tags origin | grep -q "refs/tags/$VERSION"; then
                      echo "TAG_EXISTS=true" >> $GITHUB_ENV
                  else
                      echo "TAG_EXISTS=false" >> $GITHUB_ENV
                  fi

            - name: Compilar (Build)
              run: |
                  BINARY_NAME=assinatura-${{ env.VERSION }}-${{ matrix.goos }}-${{ matrix.goarch }}
                  if [ "${{ matrix.goos }}" = "windows" ]; then BINARY_NAME=$BINARY_NAME.exe; fi

                  # Entra na pasta do CLI e compila
                  GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o $BINARY_NAME ./assinatura

            - name: Upload dos binários para a Release e adiciona tag
              uses: softprops/action-gh-release@v2
              if: env.TAG_EXISTS == 'false'
              with:
                  tag_name: ${{ env.VERSION }}
                  name: 'Releases ${{ env.VERSION }}'
                  generate_release_notes: true
                  files: assinatura-*
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
